jobs: 4
matrix:
- name: Markdown
  aspell:
    lang: en
    ignore-case: true
  dictionary:
    wordlists:
    - .github/wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.context:
      context_visible_first: true
      escapes: \\[\\`~]
      delimiters:
        # Ignore text in brackets [] and () and ""
        - open: '\['
          close: '\]'
        - open: '\('
          close: '\)'
        - open: '\{'
          close: '\}'
        - open: '\"'
          close: '\"'
  - pyspelling.filters.markdown:
      markdown_extensions:
      - pymdownx.superfences
  - pyspelling.filters.html:
      comments: false
      ignores:
      - ':matches(code, pre)'
      - 'code'
      - 'pre'
      - 'blockquote'
  sources:
  - '_posts/*.md'
  default_encoding: utf-8  