name: Spellcheck

on:
    workflow_dispatch:  # This event triggers the workflow manually

jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check Spelling
      uses: rojopolis/spellcheck-github-actions@v0
      with:
        config_path: .github/spellcheck.yml
        source_files: "_posts/*.md"
        task_name: Markdown