name: Spellcheck

on:
    workflow_dispatch:  # This event triggers the workflow manually

jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check Spelling
      uses: rojopolis/spellcheck-github-actions@v0